parameters:
- name: Retau
  value_type: real
  scan: true
  lower: -2.0
  upper: 2.0
  default: -0.011631
  prior: flat
- name: Imtau
  value_type: real
  scan: true
  lower: 0.866
  upper: 8.0
  default: 0.994666
  prior: flat
- name: n_scale
  value_type: real
  scan: false
  default: 1.0
  prior: fixed
- name: alpha
  value_type: real
  scan: true
  lower: 1.0e-5
  upper: 1.0e-3
  default: 0.0002712
  prior: log
- name: beta
  value_type: real
  scan: true
  lower: 1.0e-3
  upper: 2.0e-1
  default: 0.0565
  prior: log
- name: gamma
  value_type: real
  scan: true
  lower: 5.0e-1
  upper: 2.0
  default: 1.0
  prior: log
