parameters:
- name: Mpsi
  value_type: real
  scan: true
  lower: 1.0
  upper: 2000.0
  default: 10.12251149337993
  prior: log
- name: MN
  value_type: real
  scan: true
  lower: 100.0
  upper: 2000.0
  default: 1140.5137059200472
  prior: log
- name: Mphi
  value_type: real
  scan: true
  lower: 60.0
  upper: 2000.0
  default: 600.5980647532418
  prior: log
- name: MA1
  value_type: real
  scan: true
  lower: 100.0
  upper: 2000.0
  default: 522.9792966613403
  prior: log
- name: MH1
  value_type: real
  scan: true
  lower: 100.0
  upper: 2000.0
  default: 712.8758766040372
  prior: log
- name: MH2
  value_type: real
  scan: true
  lower: 100.0
  upper: 2000.0
  default: 501.89798124265167
  prior: log
- name: sh
  value_type: real
  scan: true
  lower: 1.0e-05
  upper: 1.0
  default: 0.3321501249654769
  prior: flat
- name: k1
  value_type: real
  scan: true
  lower: -0.1
  upper: 0.1
  default: -0.0031676437949630376
  prior: flat
- name: k4
  value_type: real
  scan: true
  lower: -0.5
  upper: 0.5
  default: 0.11799696022086778
  prior: flat
- name: Reye
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: -0.011478220392316807
  prior: flat
- name: Imgye
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: 0.017430797734482983
  prior: flat
- name: Reymu
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: -0.015713229135338982
  prior: flat
- name: Imgymu
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: 0.005250695802982697
  prior: flat
- name: Reytau
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: 0.005739250837521016
  prior: flat
- name: Imgytau
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: -0.012043977450585443
  prior: flat
- name: ReYe
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: 0.005086070155733324
  prior: flat
- name: ImgYe
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: 0.001967805442413404
  prior: flat
- name: ReYmu
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: 0.004628892469591573
  prior: flat
- name: ImgYmu
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: -0.012596860641314862
  prior: flat
- name: ReYtau
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: -0.0009276633273550029
  prior: flat
- name: ImgYtau
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: 0.013439539333703277
  prior: flat
- name: Reyp
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: 0.0047262599110235795
  prior: flat
- name: Imgyp
  value_type: real
  scan: true
  lower: -0.3
  upper: 0.3
  default: -0.010251008924842653
  prior: flat
- name: lambda1
  value_type: real
  scan: true
  lower: 1.0e-07
  upper: 0.3
  default: 0.129
  prior: log
- name: lambda2
  value_type: real
  scan: true
  lower: 1.0e-07
  upper: 0.3
  default: 0.0012675213127967295
  prior: log
- name: lambda3
  value_type: real
  scan: true
  lower: 1.0e-07
  upper: 0.3
  default: 0.0798389142274129
  prior: log
- name: k5
  value_type: real
  scan: true
  lower: 1.0e-07
  upper: 0.3
  default: 0.00014967900562753967
  prior: log
