parameters:
- name: Retau
  value_type: real
  scan: true
  lower: -0.5
  upper: 0.5
  default: 0.029725
  prior: flat
- name: Imtau
  value_type: real
  scan: true
  lower: 0.866
  upper: 3.5
  default: 1.1181
  prior: flat
- name: a2t
  value_type: real
  scan: true
  lower: -2.0
  upper: 2.0
  default: 1.7303
  prior: flat
- name: a3t
  value_type: real
  scan: true
  lower: -3.0
  upper: 3.0
  default: -2.7706
  prior: flat
- name: g2t
  value_type: real
  scan: true
  lower: -3.5
  upper: 3.5
  default: 2.716
  prior: flat
- name: g3t
  value_type: real
  scan: true
  lower: -2.0
  upper: 2.0
  default: -0.35786
  prior: flat
